# Generated by Django 3.1.4 on 2023-12-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='floor_plans.floor'),
        ),
    ]
