# Generated by Django 3.1.4 on 2023-12-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0003_auto_20231207_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor_plans.floor')),
            ],
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Desk',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
