# Generated by Django 3.1.4 on 2023-12-06 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0005_historicaldesk_historicalfloor_historicalmeeting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='floor_plans.floor'),
        ),
        migrations.AlterField(
            model_name='meeting_room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rooms', to='floor_plans.floor'),
        ),
    ]
