# Generated by Django 3.1.4 on 2023-12-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0007_changehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfloor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmeeting_room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='historicalmeeting_room',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='meeting_room',
        ),
        migrations.AddField(
            model_name='changehistory',
            name='desk_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changehistory',
            name='meeting_room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalDesk',
        ),
        migrations.DeleteModel(
            name='HistoricalFloor',
        ),
        migrations.DeleteModel(
            name='HistoricalMeeting_Room',
        ),
    ]
