# Generated by Django 3.1.4 on 2023-12-07 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0008_auto_20231207_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFloor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical floor',
                'verbose_name_plural': 'historical floors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='desk',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor_plans.floor'),
        ),
        migrations.AlterField(
            model_name='meeting_room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor_plans.floor'),
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
    ]
