# Generated by Django 3.1.4 on 2023-12-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0011_auto_20231207_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='no_of_desks',
            new_name='max_desks',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='no_of_meeting_rooms',
            new_name='max_rooms',
        ),
        migrations.RenameField(
            model_name='historicalfloor',
            old_name='no_of_desks',
            new_name='max_desks',
        ),
        migrations.RenameField(
            model_name='historicalfloor',
            old_name='no_of_meeting_rooms',
            new_name='max_rooms',
        ),
    ]
